[theme]
primaryColor = "#059669"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E3A8A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

